### ISSUE TITLE
Automatically remove archives

### ISSUE THREAD

**Issue by dantleech** [dantleech/what-changed#8]
e.g. set max number of archives to 50 or similar, should be configurable.

**Comment by Nemo64** [comment]
If the project is in git you could also ask git for the old `composer.lock`. Then you wouldn't need that archive at all and anyone could look at the changes caused by someone elses update.

**Comment by dantleech** [comment]
Only if you commit the changelock (and use GIT). But indeed there are a number of strategies.

**Comment by dantleech** [comment]
Also, it archives the lock file _before_ it updates, so you always get the changes. We could even not create an archive at all, but currently there is some benefit of checking (or re-checking) the changed log after running the update.

**Comment by dantleech** [comment]
This is redundant now, we no longer archive lock files, we just keep the old one.
